// Swedish -> English medical and scientific term synonyms used to expand
// search queries. Merged from the two previously-duplicated (and drifted)
// per-page dictionaries into a single source of truth. Keep entries sorted by
// key. Generated once via a merge script, then maintained by hand.
export const SWEDISH_TO_ENGLISH_TERMS: Record<string, string[]> = {
  "acls": ["anterior cruciate ligament","acl"],
  "alzheimer": ["alzheimer","dementia"],
  "analys": ["analysis","analytical"],
  "anatomi": ["anatomy","anatomical","body"],
  "anestesi": ["anesthesia","anesthetic"],
  "artrit": ["arthritis","rheumatoid"],
  "astma": ["asthma","respiratory"],
  "barn": ["child","pediatric","children"],
  "barnkirurgi": ["pediatric surgery","children surgery"],
  "bbmri": ["bbmri","biobanking and biomolecular resources research infrastructure"],
  "behandling": ["treatment","therapy"],
  "ben": ["bone","skeletal"],
  "beteende": ["behavioral","behaviour"],
  "biobank": ["biobank","biobanking"],
  "bioinformatik": ["bioinformatics","computational biology"],
  "biokemi": ["biochemistry","biochemical"],
  "blod": ["blood","hematological"],
  "bråckkirurgi": ["hernia surgery","hernia repair"],
  "cancer": ["cancer","tumor","neoplasia","oncology"],
  "cdc": ["cdc","centers for disease control and prevention"],
  "cellbiologi": ["cell biology","cellular"],
  "cerebralparesi": ["cerebral palsy","cp"],
  "cf": ["cystic fibrosis","cf"],
  "covid": ["covid","coronavirus"],
  "cystiskfibros": ["cystic fibrosis","cf"],
  "data": ["data","dataset"],
  "demens": ["dementia","cognitive","alzheimer"],
  "dermatit": ["dermatitis","eczema","skin condition"],
  "diabetes": ["diabetes","diabetic"],
  "diagnostik": ["diagnostics","diagnostic"],
  "dialys": ["dialysis","renal replacement"],
  "digg": ["myndigheten for digital förvaltning","digg"],
  "dysfori": ["dysphoria","gender dysphoria"],
  "ebi": ["ebi","european bioinformatics institute"],
  "ecdc": ["ecdc","european centre for disease prevention and control"],
  "elixir": ["elixir","elixir europe"],
  "embl": ["embl","european molecular biology laboratory"],
  "endokrinologi": ["endocrinology","hormonal"],
  "epidemiologi": ["epidemiology","epidemiological","epidemic"],
  "epigenetik": ["epigenetics","epigenetic","epigenome"],
  "epilepsi": ["epilepsy","seizure"],
  "epilepsikirurgi": ["epilepsy surgery","epileptic surgery"],
  "experiment": ["experiment","experimental"],
  "farmakologi": ["pharmacology","pharmaceutical","drug"],
  "fega": ["fega","federated european genome-phenome archive"],
  "fibros": ["fibrosis","scarring"],
  "folkhälsomyndigheten": ["public health agency","fohm"],
  "forskning": ["research","study"],
  "fysiologi": ["physiology","physiological"],
  "gallblåsa": ["gallbladder","biliary"],
  "gallvägar": ["bile ducts","biliary tract"],
  "gastroenterologi": ["gastroenterology","digestive"],
  "genetik": ["genetics","genetic","gene"],
  "genomik": ["genomics","genomic","genome"],
  "gravid": ["pregnant","pregnancy","maternal"],
  "gynekologi": ["gynecology","gynecological"],
  "göteborg": ["gothenburg","göteborg"],
  "handkirurgi": ["hand surgery","microsurgery"],
  "hemofili": ["hemophilia","bleeding disorder"],
  "hiv": ["hiv","aids"],
  "hjärna": ["brain","cerebral","neurological"],
  "hjärninfarkt": ["cerebral infarction","brain stroke","cerebrovascular accident","cva"],
  "hjärta": ["heart","cardiac","cardiovascular"],
  "hjärtinfarkt": ["heart attack","myocardial infarction","cardiac"],
  "hjärtkirurgi": ["cardiac surgery","heart surgery"],
  "hud": ["skin","dermatological"],
  "hydrocefalus": ["hydrocephalus","water on brain"],
  "höftfyseolys": ["slipped capital femoral epiphysis","scfe","hip slippage"],
  "höftledsinstabilitet": ["hip joint instability","hip dysplasia","ddh","developmental dysplasia of hip"],
  "immunologi": ["immunology","immune","antibody"],
  "inflammatoriskpolyneuropati": ["inflammatory polyneuropathy","chronic inflammatory demyelinating polyneuropathy","cidp"],
  "intensivvård": ["intensive care","icu","critical care"],
  "ivf": ["in vitro fertilization","ivf"],
  "kardiologi": ["cardiology","cardiac"],
  "karolinska": ["karolinska","ki","karolinska institutet"],
  "kartläggning": ["mapping","survey"],
  "katarakt": ["cataract","lens opacity"],
  "kemoterapi": ["chemotherapy","cancer treatment"],
  "kirurgi": ["surgery","surgical"],
  "klumpfot": ["clubfoot","talipes equinovarus","peva"],
  "kognitiv": ["cognitive","mental","brain function"],
  "kvalitetsregister": ["quality registry","registry"],
  "kärlkirurgi": ["vascular surgery","vessel surgery"],
  "leder": ["joint","articular"],
  "leukemi": ["leukemia","leukaemia","blood cancer"],
  "lever": ["liver","hepatic"],
  "lund": ["lund","lund university"],
  "lungor": ["lung","pulmonary","respiratory"],
  "lymfom": ["lymphoma","lymphatic cancer"],
  "läkemedel": ["drug","medication","pharmaceutical"],
  "medicin": ["medicine","medication","drug"],
  "metabolomik": ["metabolomics","metabolic","metabolite"],
  "mikrobiologi": ["microbiology","microbial","microbe"],
  "molekylärbiologi": ["molecular biology","molecular","molecule"],
  "motorneuronsjukdom": ["motor neuron disease","motor neurone disease","mnd","als","amyotrophic lateral sclerosis"],
  "ms": ["multiple sclerosis","ms"],
  "muskler": ["muscle","muscular"],
  "myasteniagravis": ["myasthenia gravis","mg","muscle weakness"],
  "myelomeningocele": ["spina bifida","neural tube defect"],
  "mätning": ["measurement","measure"],
  "narkolepsi": ["narcolepsy","sleep disorder"],
  "nationellt": ["national"],
  "nbis": ["nbis","national bioinformatics infrastructure"],
  "ncbi": ["ncbi","national center for biotechnology information"],
  "neonatal": ["newborn","neonatal","infant"],
  "nervsystem": ["nervous system","neurological"],
  "neuralrörsdefekt": ["neural tube defect","spina bifida"],
  "neurologi": ["neurology","neurological"],
  "neuromuskulärasjukdomar": ["neuromuscular diseases","neuromuscular disorders"],
  "nih": ["nih","national institutes of health"],
  "njurar": ["kidney","renal"],
  "obesitas": ["obesity","overweight"],
  "observation": ["observation","observational"],
  "onkologi": ["oncology","cancer"],
  "ortopedi": ["orthopedics","orthopedic"],
  "osteoporos": ["osteoporosis","bone"],
  "parkinson": ["parkinson","parkinson's"],
  "patellaluxation": ["patellar dislocation","kneecap dislocation","patella luxation"],
  "patologi": ["pathology","pathological","disease"],
  "perthes": ["perthes disease","legg-calve-perthes","avascular necrosis hip"],
  "prognos": ["prognosis","prognostic"],
  "proteomik": ["proteomics","proteomic","protein"],
  "prov": ["sample","specimen"],
  "psykisk": ["psychiatric","psychological","mental health"],
  "regionalt": ["regional"],
  "register": ["registry","register","database"],
  "reumatism": ["rheumatism","rheumatic","arthritis"],
  "reumatologi": ["rheumatology","rheumatic"],
  "sbdi": ["sbdi","swedish biodiversity data infrastructure"],
  "scapis": ["scapis","swedish cardiopulmonary bioimage study"],
  "scb": ["statistics sweden","scb"],
  "scilifelab": ["scilifelab","science for life laboratory"],
  "screening": ["screening"],
  "sjukhus": ["hospital","clinical"],
  "snd": ["swedish national data service","snd"],
  "socialstyrelsen": ["national board of health and welfare"],
  "spondylit": ["spondylitis","ankylosing spondylitis"],
  "spädbarn": ["infant","newborn","neonatal"],
  "stockholm": ["stockholm"],
  "stroke": ["stroke","cerebrovascular","brain"],
  "strålbehandling": ["radiation","radiotherapy"],
  "studie": ["study","research"],
  "sverige": ["sweden","swedish"],
  "svårneurovaskulärhuvudvärk": ["severe neurovascular headache","cluster headache","migraine"],
  "terapi": ["therapy","therapeutic"],
  "thoraxkirurgi": ["thoracic surgery","chest surgery"],
  "toxikologi": ["toxicology","toxic","poison"],
  "transkriptomik": ["transcriptomics","transcriptomic"],
  "transplantation": ["transplant","transplantation"],
  "undersökning": ["investigation","examination"],
  "uppföljning": ["follow-up","monitoring"],
  "uppsala": ["uppsala","uppsala university"],
  "urologi": ["urology","urological"],
  "vaccin": ["vaccine","vaccination"],
  "vetenskapsrådet": ["swedish research council","vr"],
  "vuxna": ["adult","adults"],
  "vård": ["care","healthcare"],
  "who": ["who","world health organization"],
  "äldre": ["elderly","geriatric","aging"],
  "ögon": ["eyes","ocular","ophthalmology"],
  "öron": ["ears","auditory","otology"],
};
